export const APPOINTMENT_UPDATE = 'APOINTMENT.UPDATE';
export const APPOINTMENT_CREATE = 'APOINTMENT.CREATE';

export const INVOICE_UPDATE = 'INVOICE.UPDATE';
export const INVOICE_PLANS_CHANGE = 'INVOICE.PLANS.CHANGE';

export const TREATMENT_CREATE = 'TREATMENT.CREATE';
export const TREATMENT_PLAN_STATUS_UPDATE_MULTIPLE =
  'TREATMENT_PLAN.STATUS_UPDATE_MULTIPLE';

export const USER_REGISTERED = 'USER.REGISTERED';
export const PATIENT_REGISTERED = 'PATIENT.REGISTERED';
export const PERSONNEL_REGISTERED = 'PERSONNEL.REGISTERED';

export const REVIEW_REQUEST_UPDATE = 'REVIEW_REQUEST.UPDATE';
export const REVIEW_REQUEST_CREATE = 'REVIEW_REQUEST.CREATE';

export const APPOINTMENT_DOCTOR_VACATION_ACCEPTED =
  'APPOINTMENT_DOCTOR_VACATION_ACCEPTED';
export const APPOINTMENT_ASSISTANT_VACATION_ACCEPTED =
  'APPOINTMENT_ASSISTANT_VACATION_ACCEPTED';
