export const iranCities = {
  persian: [
    {
      province: 'اردبیل',
      cities: [
        'اردبیل',
        'اصلاندوز',
        'آبی بیگلو',
        'بیله سوار',
        'پارس آباد',
        'تازه کند',
        'تازه کندانگوت',
        'جعفرآباد',
        'خلخال',
        'رضی',
        'سرعین',
        'عنبران',
        'فخرآباد',
        'کلور',
        'کوراییم',
        'گرمی',
        'گیوی',
        'لاهرود',
        'مرادلو',
        'مشگین شهر',
        'نمین',
        'نیر',
        'هشتجین',
        'هیر',
      ],
    },
    {
      province: 'اصفهان',
      cities: [
        'ابریشم',
        'ابوزیدآباد',
        'اردستان',
        'اژیه',
        'اصفهان',
        'افوس',
        'انارک',
        'ایمانشهر',
        'آران وبیدگل',
        'بادرود',
        'باغ بهادران',
        'بافران',
        'برزک',
        'برف انبار',
        'بوئین ومیاندشت',
        'بهاران شهر',
        'بهارستان',
        'پیربکران',
        'تودشک',
        'تیران',
        'جندق',
        'جوزدان',
        'جوشقان وکامو',
        'چادگان',
        'چرمهین',
        'چمگردان',
        'حبیب آباد',
        'حسن آباد',
        'حنا',
        'خالدآباد',
        'خمینی شهر',
        'خوانسار',
        'خور',
        'خوراسگان',
        'خورزوق',
        'داران',
        'دامنه',
        'درچه پیاز',
        'دستگرد',
        'دولت آباد',
        'دهاقان',
        'دهق',
        'دیزیچه',
        'رزوه',
        'رضوانشهر',
        'زاینده رود',
        'زرین شهر',
        'زواره',
        'زیباشهر',
        'سده لنجان',
        'سفیدشهر',
        'سگزی',
        'سمیرم',
        'شاپورآباد',
        'شاهین شهر',
        'شهرضا',
        'طالخونچه',
        'عسگران',
        'علویچه',
        'فرخی',
        'فریدونشهر',
        'فلاورجان',
        'فولادشهر',
        'قمصر',
        'قهجاورستان',
        'قهدریجان',
        'کاشان',
        'کرکوند',
        'کلیشادوسودرجان',
        'کمشچه',
        'کمه',
        'کوشک',
        'کوهپایه',
        'کهریزسنگ',
        'گرگاب',
        'گزبرخوار',
        'گلپایگان',
        'گلدشت',
        'گلشن',
        'گلشهر',
        'گوگد',
        'لای بید',
        'مبارکه',
        'محمدآباد',
        'مشکات',
        'منظریه',
        'مهاباد',
        'میمه',
        'نائین',
        'نجف آباد',
        'نصرآباد',
        'نطنز',
        'نوش آباد',
        'نیاسر',
        'نیک آباد',
        'ورزنه',
        'ورنامخواست',
        'وزوان',
        'ونک',
        'هرند',
      ],
    },
    {
      province: 'البرز',
      cities: [
        'اشتهارد',
        'آسارا',
        'تنکمان',
        'چهارباغ',
        'سیف آباد',
        'شهرجدیدهشتگرد',
        'طالقان',
        'کرج',
        'کمال شهر',
        'کوهسار',
        'گرمدره',
        'ماهدشت',
        'محمدشهر',
        'مشکین دشت',
        'نظرآباد',
        'هشتگرد',
      ],
    },
    {
      province: 'ایلام',
      cities: [
        'ارکواز',
        'ایلام',
        'ایوان',
        'آبدانان',
        'آسمان آباد',
        'بدره',
        'پهله',
        'توحید',
        'چوار',
        'دره شهر',
        'دلگشا',
        'دهلران',
        'زرنه',
        'سراب باغ',
        'سرابله',
        'صالح آباد',
        'لومار',
        'مورموری',
        'موسیان',
        'مهران',
        'میمه',
      ],
    },
    {
      province: 'آذربایجان شرقی',
      cities: [
        'اسکو',
        'اهر',
        'ایلخچی',
        'آبش احمد',
        'آذرشهر',
        'آقکند',
        'باسمنج',
        'بخشایش',
        'بستان آباد',
        'بناب',
        'بناب جدید',
        'تبریز',
        'ترک',
        'ترکمانچای',
        'تسوج',
        'تیکمه داش',
        'جلفا',
        'خاروانا',
        'خامنه',
        'خراجو',
        'خسروشهر',
        'خمارلو',
        'خواجه',
        'دوزدوزان',
        'زرنق',
        'زنوز',
        'سراب',
        'سردرود',
        'سیس',
        'سیه رود',
        'شبستر',
        'شربیان',
        'شرفخانه',
        'شندآباد',
        'شهرجدیدسهند',
        'صوفیان',
        'عجب شیر',
        'قره آغاج',
        'کشکسرای',
        'کلوانق',
        'کلیبر',
        'کوزه کنان',
        'گوگان',
        'لیلان',
        'مراغه',
        'مرند',
        'ملکان',
        'ممقان',
        'مهربان',
        'میانه',
        'نظرکهریزی',
        'وایقان',
        'ورزقان',
        'هادیشهر',
        'هریس',
        'هشترود',
        'هوراند',
        'یامچی',
      ],
    },
    {
      province: 'آذربایجان غربی',
      cities: [
        'ارومیه',
        'اشنویه',
        'ایواوغلی',
        'آواجیق',
        'باروق',
        'بازرگان',
        'بوکان',
        'پلدشت',
        'پیرانشهر',
        'تازه شهر',
        'تکاب',
        'چهاربرج',
        'خلیفان',
        'خوی',
        'دیزج دیز',
        'ربط',
        'سردشت',
        'سرو',
        'سلماس',
        'سیلوانه',
        'سیمینه',
        'سیه چشمه',
        'شاهین دژ',
        'شوط',
        'فیرورق',
        'قره ضیاءالدین',
        'قطور',
        'قوشچی',
        'کشاورز',
        'گردکشانه',
        'ماکو',
        'محمدیار',
        'محمودآباد',
        'مهاباد',
        'میاندوآب',
        'میرآباد',
        'نالوس',
        'نقده',
        'نوشین',
      ],
    },
    {
      province: 'بوشهر',
      cities: [
        'امام حسن',
        'انارستان',
        'اهرم',
        'آبپخش',
        'آبدان',
        'برازجان',
        'بردخون',
        'بردستان',
        'بندردیر',
        'بندردیلم',
        'بندرریگ',
        'بندرکنگان',
        'بندرگناوه',
        'بنک',
        'بوشهر',
        'تنگ ارم',
        'جم',
        'چغادک',
        'خارک',
        'خورموج',
        'دالکی',
        'دلوار',
        'ریز',
        'سعدآباد',
        'سیراف',
        'شبانکاره',
        'شنبه',
        'عسلویه',
        'کاکی',
        'کلمه',
        'نخل تقی',
        'وحدتیه',
      ],
    },
    {
      province: 'تهران',
      cities: [
        'ارجمند',
        'اسلامشهر',
        'اندیشه',
        'آبسرد',
        'آبعلی',
        'باغستان',
        'باقرشهر',
        'بومهن',
        'پاکدشت',
        'پردیس',
        'پیشوا',
        'تجریش',
        'تهران',
        'جوادآباد',
        'چهاردانگه',
        'حسن آباد',
        'دماوند',
        'رباط کریم',
        'رودهن',
        'ری',
        'شاهدشهر',
        'شریف آباد',
        'شهریار',
        'صالح آباد',
        'صباشهر',
        'صفادشت',
        'فردوسیه',
        'فرون آباد',
        'فشم',
        'فیروزکوه',
        'قدس',
        'قرچک',
        'کهریزک',
        'کیلان',
        'گلستان',
        'لواسان',
        'ملارد',
        'نسیم شهر',
        'نصیرآباد',
        'وحیدیه',
        'ورامین',
      ],
    },
    {
      province: 'چهارمحال وبختیاری',
      cities: [
        'اردل',
        'آلونی',
        'باباحیدر',
        'بروجن',
        'بلداجی',
        'بن',
        'جونقان',
        'چلگرد',
        'سامان',
        'سفیددشت',
        'سودجان',
        'سورشجان',
        'شلمزار',
        'شهرکرد',
        'طاقانک',
        'فارسان',
        'فرادنبه',
        'فرخ شهر',
        'کیان',
        'گندمان',
        'گهرو',
        'لردگان',
        'مال خلیفه',
        'ناغان',
        'نافچ',
        'نقنه',
        'هفشجان',
      ],
    },
    {
      province: 'خراسان جنوبی',
      cities: [
        'ارسک',
        'اسدیه',
        'اسفدن',
        'اسلامیه',
        'آرین شهر',
        'آیسک',
        'بشرویه',
        'بیرجند',
        'حاجی آباد',
        'خضری دشت بیاض',
        'خوسف',
        'زهان',
        'سرایان',
        'سربیشه',
        'سه قلعه',
        'شوسف',
        'طبس مسینا',
        'فردوس',
        'قائن',
        'قهستان',
        'گزیک',
        'محمد شهر',
        'مود',
        'نهبندان',
        'نیمبلوک',
      ],
    },
    {
      province: 'خراسان رضوی',
      cities: [
        'احمدآبادصولت',
        'انابد',
        'باجگیران',
        'باخرز',
        'بار',
        'بایگ',
        'بجستان',
        'بردسکن',
        'بیدخت',
        'تایباد',
        'تربت جام',
        'تربت حیدریه',
        'جغتای',
        'جنگل',
        'چاپشلو',
        'چکنه',
        'چناران',
        'خرو',
        'خلیل آباد',
        'خواف',
        'داورزن',
        'درگز',
        'درود',
        'دولت آباد',
        'رباط سنگ',
        'رشتخوار',
        'رضویه',
        'روداب',
        'ریوش',
        'سبزوار',
        'سرخس',
        'سفیدسنگ',
        'سلامی',
        'سلطان آباد',
        'سنگان',
        'شادمهر',
        'شاندیز',
        'ششتمد',
        'شهرآباد',
        'شهرزو',
        'صالح آباد',
        'طرقبه',
        'عشق آباد',
        'فرهادگرد',
        'فریمان',
        'فیروزه',
        'فیض آباد',
        'قاسم آباد',
        'قدمگاه',
        'قلندرآباد',
        'قوچان',
        'کاخک',
        'کاریز',
        'کاشمر',
        'کدکن',
        'کلات',
        'کندر',
        'گلمکان',
        'گناباد',
        'لطف آباد',
        'مزدآوند',
        'مشهد',
        'مشهدریزه',
        'ملک آباد',
        'نشتیفان',
        'نصر آباد',
        'نقاب',
        'نوخندان',
        'نیشابور',
        'نیل شهر',
        'همت آباد',
        'یونسی',
      ],
    },
    {
      province: 'خراسان شمالی',
      cities: [
        'اسفراین',
        'ایور',
        'آشخانه',
        'بجنورد',
        'پیش قلعه',
        'تیتکانلو',
        'جاجرم',
        'حصارگرمخان',
        'درق',
        'راز',
        'سنخواست',
        'شوقان',
        'شیروان',
        'صفی آباد',
        'فاروج',
        'قاضی',
        'گرمه',
        'لوجلی',
      ],
    },
    {
      province: 'خوزستان',
      cities: [
        'اروندکنار',
        'الوان',
        'امیدیه',
        'اندیمشک',
        'اهواز',
        'ایذه',
        'آبادان',
        'آغاجاری',
        'باغ ملک',
        'بستان',
        'بندرامام خمینی',
        'بندرماهشهر',
        'بهبهان',
        'ترکالکی',
        'جایزان',
        'جنت مکان',
        'چغامیش',
        'چمران',
        'چوئبده',
        'حر',
        'حسینیه',
        'حمزه',
        'حمیدیه',
        'خرمشهر',
        'دارخوین',
        'دزآب',
        'دزفول',
        'دهدز',
        'رامشیر',
        'رامهرمز',
        'رفیع',
        'زهره',
        'سالند',
        'سردشت',
        'سماله',
        'سوسنگرد',
        'شادگان',
        'شاوور',
        'شرافت',
        'شوش',
        'شوشتر',
        'شیبان',
        'صالح شهر',
        'صالح مشطط',
        'صفی آباد',
        'صیدون',
        'قلعه تل',
        'قلعه خواجه',
        'گتوند',
        'گوریه',
        'لالی',
        'مسجدسلیمان',
        'مشراگه',
        'مقاومت',
        'ملاثانی',
        'میانرود',
        'میداود',
        'مینوشهر',
        'ویس',
        'هفتگل',
        'هندیجان',
        'هویزه',
      ],
    },
    {
      province: 'زنجان',
      cities: [
        'ابهر',
        'ارمغانخانه',
        'آب بر',
        'چورزق',
        'حلب',
        'خرمدره',
        'دندی',
        'زرین آباد',
        'زرین رود',
        'زنجان',
        'سجاس',
        'سلطانیه',
        'سهرورد',
        'صائین قلعه',
        'قیدار',
        'گرماب',
        'ماه نشان',
        'هیدج',
      ],
    },
    {
      province: 'سمنان',
      cities: [
        'امیریه',
        'ایوانکی',
        'آرادان',
        'بسطام',
        'بیارجمند',
        'دامغان',
        'درجزین',
        'دیباج',
        'سرخه',
        'سمنان',
        'شاهرود',
        'شهمیرزاد',
        'کلاته خیج',
        'گرمسار',
        'مجن',
        'مهدی شهر',
        'میامی',
      ],
    },
    {
      province: 'سیستان وبلوچستان',
      cities: [
        'ادیمی',
        'اسپکه',
        'ایرانشهر',
        'بزمان',
        'بمپور',
        'بنت',
        'بنجار',
        'پیشین',
        'جالق',
        'چاه بهار',
        'خاش',
        'دوست محمد',
        'راسک',
        'زابل',
        'زابلی',
        'زاهدان',
        'زرآباد',
        'زهک',
        'سراوان',
        'سرباز',
        'سوران',
        'سیرکان',
        'علی اکبر',
        'فنوج',
        'قصرقند',
        'کنارک',
        'گشت',
        'گلمورتی',
        'محمدان',
        'محمد آباد',
        'محمدی',
        'میرجاوه',
        'نصرت آباد',
        'نگور',
        'نوک آباد',
        'نیک شهر',
        'هیدوج',
      ],
    },
    {
      province: 'فارس',
      cities: [
        'اردکان',
        'ارسنجان',
        'استهبان',
        'اسیر',
        'اشکنان',
        'افزر',
        'اقلید',
        'امام شهر',
        'اوز',
        'اهل',
        'ایج',
        'ایزدخواست',
        'آباده',
        'آباده طشک',
        'باب انار',
        'بالاده',
        'بنارویه',
        'بوانات',
        'بهمن',
        'بیرم',
        'بیضا',
        'جنت شهر',
        'جویم',
        'جهرم',
        'حاجی آباد',
        'حسامی',
        'حسن آباد',
        'خانه زنیان',
        'خاوران',
        'خرامه',
        'خشت',
        'خنج',
        'خور',
        'خومه زار',
        'داراب',
        'داریان',
        'دبیران',
        'دژکرد',
        'دوبرجی',
        'دوزه',
        'دهرم',
        'رامجرد',
        'رونیز',
        'زاهدشهر',
        'زرقان',
        'سده',
        'سروستان',
        'سعادت شهر',
        'سورمق',
        'سیدان',
        'ششده',
        'شهر جدید صدرا',
        'شهرپیر',
        'شیراز',
        'صغاد',
        'صفاشهر',
        'علامرودشت',
        'عمادده',
        'فدامی',
        'فراشبند',
        'فسا',
        'فیروزآباد',
        'قادرآباد',
        'قائمیه',
        'قطب آباد',
        'قطرویه',
        'قیر',
        'کارزین',
        'کازرون',
        'کامفیروز',
        'کره ای',
        'کنارتخته',
        'کوار',
        'کوهنجان',
        'گراش',
        'گله دار',
        'لار',
        'لامرد',
        'لپوئی',
        'لطیفی',
        'مبارک آباد',
        'مرودشت',
        'مشکان',
        'مصیری',
        'مهر',
        'میمند',
        'نوبندگان',
        'نوجین',
        'نودان',
        'نورآباد',
        'نی ریز',
        'وراوی',
        'هماشهر',
      ],
    },
    {
      province: 'قزوین',
      cities: [
        'ارداق',
        'اسفرورین',
        'اقبالیه',
        'الوند',
        'آبگرم',
        'آبیک',
        'آوج',
        'بوئین زهرا',
        'بیدستان',
        'تاکستان',
        'خاکعلی',
        'خرمدشت',
        'دانسفهان',
        'رازمیان',
        'سگزآباد',
        'سیردان',
        'شال',
        'شریفیه',
        'ضیاءآباد',
        'قزوین',
        'کوهین',
        'محمدیه',
        'محمودآبادنمونه',
        'معلم کلایه',
        'نرجه',
      ],
    },
    {
      province: 'قم',
      cities: ['جعفریه', 'دستجرد', 'سلفچگان', 'قم', 'قنوات', 'کهک'],
    },
    {
      province: 'کردستان',
      cities: [
        'آرمرده',
        'بابارشانی',
        'بانه',
        'بلبان آباد',
        'بوئین سفلی',
        'بیجار',
        'چناره',
        'دزج',
        'دلبران',
        'دهگلان',
        'دیواندره',
        'زرینه',
        'سروآباد',
        'سریش آباد',
        'سقز',
        'سنندج',
        'شویشه',
        'صاحب',
        'قروه',
        'کامیاران',
        'کانی دینار',
        'کانی سور',
        'مریوان',
        'موچش',
        'یاسوکند',
      ],
    },
    {
      province: 'کرمان',
      cities: [
        'اختیارآباد',
        'ارزوئیه',
        'امین شهر',
        'انار',
        'اندوهجرد',
        'باغین',
        'بافت',
        'بردسیر',
        'بروات',
        'بزنجان',
        'بم',
        'بهرمان',
        'پاریز',
        'جبالبارز',
        'جوپار',
        'جوزم',
        'جیرفت',
        'چترود',
        'خاتون آباد',
        'خانوک',
        'خورسند',
        'درب بهشت',
        'دوساری',
        'دهج',
        'رابر',
        'راور',
        'راین',
        'رفسنجان',
        'رودبار',
        'ریحان شهر',
        'زرند',
        'زنگی آباد',
        'زیدآباد',
        'سرچشمه',
        'سیرجان',
        'شهداد',
        'شهربابک',
        'صفائیه',
        'عنبرآباد',
        'فاریاب',
        'فهرج',
        'قلعه گنج',
        'کاظم آباد',
        'کرمان',
        'کشکوئیه',
        'کوهبنان',
        'کهنوج',
        'کیانشهر',
        'گلباف',
        'گلزار',
        'لاله زار',
        'ماهان',
        'محمد آباد',
        'محی آباد',
        'مردهک',
        'منوجان',
        'نجف شهر',
        'نرماشیر',
        'نظام شهر',
        'نگار',
        'نودژ',
        'هجدک',
        'هماشهر',
        'یزدان شهر',
      ],
    },
    {
      province: 'کرمانشاه',
      cities: [
        'ازگله',
        'اسلام آبادغرب',
        'باینگان',
        'بیستون',
        'پاوه',
        'تازه آباد',
        'جوانرود',
        'حمیل',
        'رباط',
        'روانسر',
        'سرپل ذهاب',
        'سرمست',
        'سطر',
        'سنقر',
        'سومار',
        'شاهو',
        'صحنه',
        'قصرشیرین',
        'کرمانشاه',
        'کرندغرب',
        'کنگاور',
        'کوزران',
        'گهواره',
        'گیلانغرب',
        'میان راهان',
        'نودشه',
        'نوسود',
        'هرسین',
        'هلشی',
      ],
    },
    {
      province: 'کهگیلویه وبویراحمد',
      cities: [
        'باشت',
        'پاتاوه',
        'چرام',
        'چیتاب',
        'دوگنبدان',
        'دهدشت',
        'دیشموک',
        'سوق',
        'سی سخت',
        'قلعه رئیسی',
        'گراب سفلی',
        'لنده',
        'لیکک',
        'مادوان',
        'مارگون',
        'یاسوج',
      ],
    },
    {
      province: 'گلستان',
      cities: [
        'انبارآلوم',
        'اینچه برون',
        'آزادشهر',
        'آق قلا',
        'بندرگز',
        'ترکمن',
        'جلین',
        'خان ببین',
        'دلند',
        'رامیان',
        'سرخنکلاته',
        'سیمین شهر',
        'علی آباد',
        'فاضل آباد',
        'کردکوی',
        'کلاله',
        'گالیکش',
        'گرگان',
        'گمیش تپه',
        'گنبد کاووس',
        'مراوه تپه',
        'مینودشت',
        'نگین شهر',
        'نوده خاندوز',
        'نوکنده',
      ],
    },
    {
      province: 'گیلان',
      cities: [
        'احمدسرگوراب',
        'اسالم',
        'اطاقور',
        'املش',
        'آستارا',
        'آستانه اشرفیه',
        'بازارجمعه',
        'بره سر',
        'بندرانزلی',
        'پره سر',
        'توتکابن',
        'جیرنده',
        'چابکسر',
        'چاف وچمخاله',
        'چوبر',
        'حویق',
        'خشکبیجار',
        'خمام',
        'دیلمان',
        'رانکوه',
        'رحیم آباد',
        'رستم آباد',
        'رشت',
        'رضوانشهر',
        'رودبار',
        'رودبنه',
        'رودسر',
        'سنگر',
        'سیاهکل',
        'شفت',
        'شلمان',
        'صومعه سرا',
        'فومن',
        'کلاچای',
        'کوچصفهان',
        'کومله',
        'کیاشهر',
        'گوراب زرمیخ',
        'لاهیجان',
        'لشت نشاء',
        'لنگرود',
        'لوشان',
        'لولمان',
        'لوندویل',
        'لیسار',
        'ماسال',
        'ماسوله',
        'مرجقل',
        'منجیل',
        'واجارگاه',
        'هشتپر',
      ],
    },
    {
      province: 'لرستان',
      cities: [
        'ازنا',
        'اشترینان',
        'الشتر',
        'الیگودرز',
        'بروجرد',
        'پلدختر',
        'چالانچولان',
        'چغلوندی',
        'چقابل',
        'خرم آباد',
        'درب گنبد',
        'دورود',
        'زاغه',
        'سپیددشت',
        'سراب دوره',
        'شول آباد',
        'فیروز آباد',
        'کونانی',
        'کوهدشت',
        'گراب',
        'معمولان',
        'مؤمن آباد',
        'نور آباد',
        'ویسیان',
        'هفت چشمه',
      ],
    },
    {
      province: 'مازندران',
      cities: [
        'امیرکلا',
        'ایزدشهر',
        'آلاشت',
        'آمل',
        'بابل',
        'بابلسر',
        'بلده',
        'بهشهر',
        'بهنمیر',
        'پل سفید',
        'پول',
        'تنکابن',
        'جویبار',
        'چالوس',
        'چمستان',
        'خرم آباد',
        'خلیل شهر',
        'خوش رودپی',
        'دابودشت',
        'رامسر',
        'رستمکلا',
        'رویان',
        'رینه',
        'زرگر محله',
        'زیرآب',
        'ساری',
        'سرخرود',
        'سلمان شهر',
        'سورک',
        'شیرگاه',
        'شیرود',
        'عباس آباد',
        'فریدونکنار',
        'فریم',
        'قائم شهر',
        'کتالم وسادات شهر',
        'کلارآباد',
        'کلاردشت',
        'کله بست',
        'کوهی خیل',
        'کیاسر',
        'کیاکلا',
        'گتاب',
        'گزنک',
        'گلوگاه',
        'محمود آباد',
        'مرزن آباد',
        'مرزیکلا',
        'نشتارود',
        'نکا',
        'نور',
        'نوشهر',
      ],
    },
    {
      province: 'مرکزی',
      cities: [
        'اراک',
        'آستانه',
        'آشتیان',
        'پرندک',
        'تفرش',
        'توره',
        'جاورسیان',
        'خشکرود',
        'خمین',
        'خنداب',
        'داودآباد',
        'دلیجان',
        'رازقان',
        'زاویه',
        'ساروق',
        'ساوه',
        'سنجان',
        'شازند',
        'شهرجدیدمهاجران',
        'غرق آباد',
        'فرمهین',
        'قورچی باشی',
        'کرهرود',
        'کمیجان',
        'مأمونیه',
        'محلات',
        'میلاجرد',
        'نراق',
        'نوبران',
        'نیمور',
        'هندودر',
      ],
    },
    {
      province: 'هرمزگان',
      cities: [
        'ابوموسی',
        'بستک',
        'بندرجاسک',
        'بندرچارک',
        'بندرعباس',
        'بندرلنگه',
        'بیکاه',
        'پارسیان',
        'تخت',
        'جناح',
        'حاجی آباد',
        'خمیر',
        'درگهان',
        'دهبارز',
        'رویدر',
        'زیارتعلی',
        'سردشت بشاگرد',
        'سرگز',
        'سندرک',
        'سوزا',
        'سیریک',
        'فارغان',
        'فین',
        'قشم',
        'قلعه قاضی',
        'کنگ',
        'کوشکنار',
        'کیش',
        'گوهران',
        'میناب',
        'هرمز',
        'هشتبندی',
      ],
    },
    {
      province: 'همدان',
      cities: [
        'ازندریان',
        'اسدآباد',
        'برزول',
        'بهار',
        'تویسرکان',
        'جورقان',
        'جوکار',
        'دمق',
        'رزن',
        'زنگنه',
        'سامن',
        'سرکان',
        'شیرین سو',
        'صالح آباد',
        'فامنین',
        'فرسفج',
        'فیروزان',
        'قروه در جزین',
        'قهاوند',
        'کبودرآهنگ',
        'گل تپه',
        'گیان',
        'لالجین',
        'مریانج',
        'ملایر',
        'نهاوند',
        'همدان',
      ],
    },
    {
      province: 'یزد',
      cities: [
        'ابرکوه',
        'احمدآباد',
        'اردکان',
        'اشکذر',
        'بافق',
        'بفروئیه',
        'بهاباد',
        'تفت',
        'حمیدیا',
        'خضرآباد',
        'دیهوک',
        'زارچ',
        'شاهدیه',
        'طبس',
        'عشق آباد',
        'عقدا',
        'مروست',
        'مهردشت',
        'مهریز',
        'میبد',
        'ندوشن',
        'نیر',
        'هرات',
        'یزد',
      ],
    },
  ],
  english: [
    {
      province: 'Ardebil',
      cities: [
        'Ardebil',
        'Islandoz',
        'Abi Bigelow',
        'Bille Savar',
        'Parsabad',
        'Taze Kand',
        'Taze Kendangot',
        'Jafarabad',
        'Khalkal',
        'Razi',
        'Sarin',
        'Anbaran',
        'Fakhrabad',
        'kelor',
        'Kooraieem',
        'Garmi',
        'Giwi',
        'Lahrud',
        'Moradlo',
        'Meshkin Shahr',
        'Namin',
        'Nair',
        'Hashtjin',
        'heir',
      ],
    },
    {
      province: 'Esfahan',
      cities: [
        'Abrisham',
        'Abuzidabad',
        'Ardestan',
        'Aegean',
        'Esfahan',
        'Oops',
        'anarch',
        'Imanshahr',
        'Aran Vebidgol',
        'Greetings',
        'Bagh Bahadran',
        'buffers',
        'Brazek',
        'Snow Barn',
        'Boyin and Miandasht',
        'Baharan Shahr',
        'Spring',
        'Pierbakran',
        'Todeshk',
        'Tirana',
        'Jandaq',
        'Jozdan',
        'Joshkan and Camo',
        'Chadgan',
        'Leather',
        'turnip',
        'Habibabad',
        'Hassan Abad',
        'Henna',
        'Khaldabad',
        'Khomeini shahr',
        'Khansar',
        'Eat',
        'Khorasgan',
        'Khorzouk',
        'Daran',
        'Domain',
        'Drache Onion',
        'Handsman',
        'Dolat abad',
        'peasant',
        'Dahgh',
        'Diziche',
        'thread',
        'Rizvanshahr',
        'Zayandeh Rood River',
        'Golden City',
        'Zawarah',
        'Beautiful city',
        'Lanjan Century',
        'White City',
        'sexy',
        'Samiram',
        'Shapurabad',
        'Shahin Shahr',
        'Shahreza',
        'Talkhonche',
        'Soldiers',
        'Alaviche',
        'Farrokhi',
        'Feridonshahr',
        'Flowerjan',
        'Foladshahr',
        'Qamar',
        'Kahejavaristan',
        'Qahdrijan',
        'Kashan',
        'Richone',
        'Klishadosudrejan',
        'Kameshcha',
        'low',
        'Kushk',
        'foothill',
        'Khriz Sang',
        'Wolf',
        'Grower',
        'Golpayegan',
        'Goldasht',
        'garden',
        'Golshahr',
        'Gogged',
        'Lay Bid',
        'Mobarake',
        'Mohammadabad',
        'Difficulties',
        'Theory',
        'Mahabad',
        'meme',
        'Nain',
        'Najaf Abad',
        'Nasrabad',
        'Satire',
        'Nooshabad',
        'Niaser',
        'Nikabad',
        'Vorzene',
        'Application',
        'Wazwan',
        'wonk',
        'Hernd',
      ],
    },
    {
      province: 'Alborz',
      cities: [
        'Eshthard',
        'Asara',
        'Tankman',
        'Four garden',
        'Saifabad',
        'New City of Hashtgerd',
        'Taleqan',
        'Karaj',
        'Perfection of the city',
        'Mountain',
        'Garmdare',
        'Mahadesht',
        'Mohammadshahr',
        'Meshkin Dasht',
        'Nazarabad',
        'Hashtgerd',
      ],
    },
    {
      province: 'Ilam',
      cities: [
        'Arquaz',
        'Ilam',
        'Porch',
        'Abadanan',
        'Asman Abad',
        'Badre',
        'Side',
        'Oneness',
        'Chavar',
        'City Valley',
        'Delgosha',
        'Dehlaran',
        'Zarne',
        'Sarab Bagh',
        'Sarabeleh',
        'Saleh Abad',
        'Lumar',
        'Mormurry',
        'Mossian',
        'Mehran',
        'meme',
      ],
    },
    {
      province: 'East Azarbaijan',
      cities: [
        'Esco',
        'Ahr',
        'Ilakhchi',
        'Abash Ahmed',
        'Azershahr',
        'Aqkand',
        'Basmanj',
        'forgiveness',
        'Bostan Abad',
        'Banab',
        'new brand',
        'Tabriz',
        'Turkish',
        'Turkmanchai',
        'Tasuj',
        'Tikeme Dash',
        'Jolfa',
        'Kharwana',
        'Khamene',
        'Kharajo',
        'Khosrowshahr',
        'Khamarlo',
        'Eunuch',
        'Embroiders',
        'smart',
        'Zenouz',
        'Mirage',
        'headache',
        'sis',
        'Black River',
        'Shelter',
        'Sharbian',
        'Sharf Khane',
        'Shandabad',
        'New City of Sahand',
        'Sufis',
        'Wow milk',
        'Qara Aghaj',
        'Kashksharai',
        'Kolwanq',
        'Caliber',
        'Kuze Kanan',
        'Gauguin',
        'Leilan',
        'Maragheh',
        'dying',
        'Malkan',
        'Possible',
        'kind',
        'Middle',
        'Nazar Kehrizi',
        'Vaiqan',
        'Varzaghan',
        'Hadishahr',
        'Harris',
        'Oshtrod',
        'Horand',
        'Yamchi',
      ],
    },
    {
      province: 'Western Azerbaijan',
      cities: [
        'Orumieh',
        'auditory',
        'Ivaoghly',
        'Avajik',
        'Baruch',
        'merchant',
        'Buchan',
        'Paldasht',
        'Piranshahr',
        'New City',
        'Taqab',
        'Charbarj',
        'Caliphs',
        'Mood',
        'Dizzy Dizzy',
        'connection',
        'Sardasht',
        'Cedar',
        'Selmas',
        'Silvane',
        'Simina',
        'Third Springs',
        'Sahin Dej',
        'shot',
        'Firouq',
        'Qara Ziauddin',
        'thick',
        'Qoshchi',
        'Farmer',
        'Slaughterhouse',
        'Mako',
        'Mohammedyar',
        'Mahmoudabad',
        'Mahabad',
        'Miandoab',
        'Mirabad',
        'Nalos',
        'cash',
        'nooshin',
      ],
    },
    {
      province: 'Bushehr',
      cities: [
        'Imam Hasan',
        'Pomegranate',
        'lever',
        'sprinkler',
        'Abadan',
        'Brazjan',
        'Bardblood',
        'Bardestan',
        'Bandardir',
        'Bandardilem',
        'Banderrig',
        'Benderkangan',
        'Bandragnave',
        'bank',
        'Bushehr',
        'I miss you',
        'Jam',
        'ChagaDak',
        'thorn',
        'Khormouj',
        'Dalkey',
        'Brave',
        'small',
        'Saad Abad',
        'Siraf',
        'Shabankare',
        'Saturday',
        'Honey',
        'Kaki',
        'Word',
        'Taqi Palm',
        'Vahad Tiyeh',
      ],
    },
    {
      province: 'Tehran',
      cities: [
        'Arjamnd',
        'Islamshahr',
        'Thought',
        'cold water',
        'Abali',
        'Garden',
        'Baqershahr',
        'Bohmann',
        'Pakdasht',
        'Pardis',
        'Leader',
        'Tajrish',
        'Tehran',
        'Javadabad',
        'Quadruple',
        'Hassan Abad',
        'Damavand',
        'Rabat Karim',
        'river',
        'Rey',
        'Shahidshahr',
        'Sharifabad',
        'Shahriar',
        'Saleh Abad',
        'Sabashahr',
        'Safadasht',
        'Ferdowsia',
        'Fron Abad',
        'Fishm',
        'Firouzkoh',
        'Ghods',
        'Ratchak',
        'Kahrizak',
        'Kelan',
        'Golestan',
        'Lovasan',
        'Mallard',
        'City Breeze',
        'Nasirabad',
        'Vahidiya',
        'Varamin',
      ],
    },
    {
      province: 'Chaharmahal va Bakhtiari',
      cities: [
        'Ardle',
        'Aloni',
        'Babahidar',
        'Brojan',
        'Bulladaji',
        'Ben',
        'Jungan',
        'Wanderer',
        'Saman',
        'Sefid Dasht',
        'Sudjan',
        'Sureshjan',
        'Shalmazar',
        'Shahr e Kord',
        'Tagank',
        'Forsan',
        'Faradanbeh',
        'Farrokh Shahr',
        'oligarch',
        'Gandoman',
        'Gharu',
        'Lords',
        'Mal Khalifa',
        'Naghan',
        'Nafech',
        'trick',
        'Hafeshjan',
      ],
    },
    {
      province: 'southern Khorasan',
      cities: [
        'ارسک',
        'اسدیه',
        'اسفدن',
        'اسلامیه',
        'آرین شهر',
        'آیسک',
        'بشرویه',
        'بیرجند',
        'حاجی آباد',
        'خضری دشت بیاض',
        'خوسف',
        'زهان',
        'سرایان',
        'سربیشه',
        'سه قلعه',
        'شوسف',
        'طبس مسینا',
        'فردوس',
        'قائن',
        'قهستان',
        'گزیک',
        'محمد شهر',
        'مود',
        'نهبندان',
        'نیمبلوک',
      ],
    },
    {
      province: 'Khorasan Razavi',
      cities: [
        'Ahmedabad Solat',
        'Enabod',
        'Extortionists',
        'Bakhrez',
        'Bar',
        'Bayg',
        'Bajistan',
        'Breadscan',
        'undressed',
        'Tybad',
        'Torbat',
        'Torbat',
        'Jaghtai',
        'Jungle',
        'Chapshlo',
        'pick',
        'Plantains',
        'Eat',
        'Khalil Abad',
        'sleep',
        'Judge',
        'Drags',
        'Hello',
        'Dolat abad',
        'ligament of stone',
        'The Gluttony',
        'Razavih',
        'Rudab',
        'Riosh',
        'green',
        'fern',
        'white stone',
        'Hello',
        'Sultanabad',
        'Sangan',
        'Shadmehr',
        'Shandiz',
        'Sixty',
        'Shahrabad',
        'Shahrezo',
        'Saleh Abad',
        'Turqaba',
        'Ashgabat',
        'Farhadgerd',
        'Command',
        'turquoise',
        'Faizabad',
        'Gasem Abad',
        'Football',
        'Qalandarabad',
        'Quchan',
        'Palace',
        'Cariz',
        'cashmere',
        'codec',
        'Klat',
        'Frankincense',
        'Golmakan',
        'Gonabad',
        'Latfabad',
        'Mazdaavand',
        'Mashhad',
        'Mashhadrizeh',
        'Malkabad',
        'Nashtifan',
        'Nasr Abad',
        'mask',
        'Laughing',
        'neyshabour',
        'Nile City',
        'Hematabad',
        'Younis',
      ],
    },
    {
      province: 'North Khorasan',
      cities: [
        'Esfarrayen',
        'Ever',
        'Kitchen',
        'Bojnord',
        'before the castle',
        'Titkanlo',
        'Jajram',
        'Hesar Garmkhan',
        'Understand',
        'Mystery',
        'Request',
        'Shoqan',
        'Shirvan',
        'Safi Abad',
        'Farouj',
        'Judge',
        'it is hot',
        'Logley',
      ],
    },
    {
      province: 'Khuzestan',
      cities: [
        'Arvandkanar',
        'colors',
        'hope',
        'Andimeshk',
        'Ahvaz',
        'Izeh',
        'Abadan',
        'Aghajari',
        'Bagh Malik',
        'garden',
        'Imam Khomeini seaport',
        'Bandarmahshahr',
        'Behbahan',
        'Terkalki',
        'Awards',
        'Paradise',
        'Chagamish',
        'Chamran',
        'Chubbede',
        'free',
        'Hosseini',
        'Hamza',
        'Hamidia',
        'Khorramshahr',
        'darkhoin',
        'watershed',
        'Dezful',
        'Heads',
        'Ramshir',
        'Ramhormoz',
        'Rafi',
        'Venus',
        'Saland',
        'Sardasht',
        'Samala',
        'Sansengard',
        'Happy',
        'shower',
        'Honor',
        'Sush',
        'Shushtar',
        'slope',
        'Saleh Shahr',
        'Saleh Mushatt',
        'Safi Abad',
        'Sidon',
        'Tel Castle',
        'Castle of Khwaja',
        'they can',
        'Guria',
        'Lally',
        'Mosque of Suleiman',
        'Meshrageh',
        'Resistance',
        'Malathani',
        'Mianrud',
        'runs',
        'Minoshahr',
        'Weiss',
        'Heftgol',
        'Indian',
        'Hoize',
      ],
    },
    {
      province: 'Zanjan',
      cities: [
        'Abhar',
        'Armaghankhane',
        'Ab bar',
        'Churzag',
        'Aleppo',
        'Khormadre',
        'Dandy',
        'Zarin Abad',
        'Golden River',
        'Zanjan',
        'Sejas',
        'Sultanieh',
        'Sehrvard',
        'Sain Qala',
        'Gaidar',
        'Warm',
        'Moon Sign',
        'Hedge',
      ],
    },
    {
      province: 'Semnan',
      cities: [
        'Amiriya',
        'Ivanki',
        'Aradan',
        'Bastam',
        'Awesome',
        'Damghan',
        'Derzin',
        'Introduction',
        'Red',
        'Semnan',
        'Shahrud',
        'Shahmirzad',
        'Kalate Khaij',
        'Garmsar',
        'mad',
        'Mehdi Shahr',
        'Miami',
      ],
    },
    {
      province: 'Sistan va Baluchestan',
      cities: [
        'Adimi',
        'Speke',
        'Iranshahr',
        'time',
        'Bampur',
        'Bennett',
        'Banjar',
        'Previous',
        'Interesting',
        'Spring Well',
        'itch',
        "Mohammad's friend",
        'Rusk',
        'Zabel',
        'Zabli',
        'Zahedan',
        'Zarabad',
        'drain',
        'Captain',
        'soldier',
        'Soran',
        'Vinegar',
        'Ali Akbar',
        'Fanuj',
        'Qasrqand',
        'beside',
        'patrol',
        'Galmorety',
        'Muhammadan',
        'Mohammed Abad',
        'Mohammadi',
        'Mirjave',
        'Nusrat Abad',
        "Don't look",
        'Nuk Abad',
        'Nick Shahr',
        'Hideju',
      ],
    },
    {
      province: 'fars',
      cities: [
        'Ardakan',
        'Arsenjan',
        'Estehban',
        'captive',
        'Ashkanan',
        'Efzer',
        'Euclid',
        'Imam of the city',
        'Oz',
        'of',
        'Edge',
        'Request',
        'Abadah',
        'Abadeh Tashk',
        'Bob Anar',
        'up',
        'Banaruyeh',
        'Bowanat',
        'Avalanche',
        "I'll go",
        'oval',
        'Paradise City',
        'Joyim',
        'Jahram',
        'Haji Abad',
        'Hosami',
        'Hassan Abad',
        "Women's House",
        'Orients',
        'scum',
        'clay',
        'Khanj',
        'Eat',
        'The Meadow',
        'Darab',
        'they have',
        'Teachers',
        'Fortress',
        'double tower',
        'dosage',
        'Dahram',
        'Ramjared',
        'Roniz',
        'Zahedshahr',
        'Zarkan',
        'Century',
        'Service',
        'Happiness of the city',
        'Sormoq',
        'Sedan',
        'six',
        'New city of Sadra',
        'Shahrpir',
        'Shiraz',
        'Sogad',
        'Safashahr',
        'Alamrodasht',
        'Emadadeh',
        'Fedami',
        'bedspread',
        'Fasa',
        'Firouzabad',
        'Qadrabad',
        'Permanent',
        'Qutababad',
        'Qatar',
        'bitumen',
        'Carzin',
        'Kazeron',
        'Camfirose',
        'Korean',
        'next door',
        'Quar',
        'Kohanjan',
        'Grash',
        'Shepherd',
        'Lar',
        'Lamerd',
        'Lepoi',
        'subtle',
        'Mubarak Abad',
        'Marvdasht',
        'Doubtful',
        'destiny',
        'stamp',
        'Memand',
        'newcomers',
        'teens',
        'Nodan',
        'Noorabad',
        'Neyriz',
        'Veravi',
        'Homashahr',
      ],
    },
    {
      province: 'Qazvin',
      cities: [
        'Ardaq',
        'Spherorin',
        'Acceptance',
        'Alvand',
        'Hot water',
        'Abic',
        'Top',
        'Boin Zahra',
        'Bidistan',
        'Vineyard',
        'Khakali',
        'Khormadasht',
        'Scientists',
        'Razmian',
        'Segsabad',
        'Sirdan',
        'shawl',
        'Honorable',
        'Ziaabad',
        'Qazvin',
        'Cohen',
        'Mohammadiyah',
        'Mahmoud Abadmoneh',
        'Teacher Hat',
        'Norja',
      ],
    },
    {
      province: 'Qom',
      cities: ['Jafarieyh', 'Dastjerd', 'Selfchgan', 'Qom', 'Qanavat', 'Kahak'],
    },
    {
      province: 'Kurdistan',
      cities: [
        'armored',
        'Babarshani',
        'Bane',
        'Balban Abad',
        'Lower Boin',
        'Bajar',
        'sycamore',
        'Dezaj',
        'Lovers',
        'Dehghlan',
        'Divander',
        'Golden',
        'Serovabad',
        'Serishabad',
        'turpentine',
        'Sanandaj',
        'sink',
        'owner',
        'Karwa',
        'Kamiaran',
        'Kani Dinar',
        'Connie Sur',
        'Marivan',
        'Sprain',
        'Yasukand',
      ],
    },
    {
      province: 'Kerman',
      cities: [
        'Akhtarabad',
        'desire',
        'Amin Shahr',
        'Pomegranate',
        'Sadness',
        'gardeners',
        'Texture',
        'Bardsir',
        'Broat',
        'Banjan',
        'Bam',
        'Behrman',
        'Paris',
        'Mountains',
        'Jupar',
        'Josem',
        'Jiroft',
        'Chetrod',
        'Khatoon Abad',
        'Khanok',
        'pleased',
        "Heaven's Gate",
        'duality',
        'Dahj',
        'rubber',
        'Rover',
        'Rhine',
        'Rafsanjan',
        'river',
        'Basil Shahr',
        'Zarden',
        'Zangi Abad',
        'Zidabad',
        'source',
        'Sirjan',
        'Shahdad',
        'Shahrbabak',
        'Safaye',
        'Anbarabad',
        'Faryab',
        'Fahraj',
        'Treasure Castle',
        'Kazhamabad',
        'Kerman',
        'Cashkoye',
        'mountaineers',
        'Khanuj',
        'Kianshahr',
        'Golbaf',
        'Golzar',
        'Tulips',
        'Mahan',
        'Mohammed Abad',
        'Mohiabad',
        'Mardhak',
        'Manujan',
        'Najaf City',
        'Narmashir',
        'city system',
        'Negar',
        'Nodge',
        'Octopus',
        'Homashahr',
        'Yazdan Shahr',
      ],
    },
    {
      province: 'Kermanshah',
      cities: [
        'Ezgele',
        'Islamabad Gharb',
        'Bayangan',
        'Bistoon',
        'Pave',
        'Taze Abad',
        'Juanrud',
        'Homail',
        'Robat',
        'Ravenser',
        'Sarpol Zahab',
        'Saramst',
        'Satr',
        'Songhor',
        'Somar',
        'Shahu',
        'Sahne',
        'Ghasre Shirin',
        'Kermanshah',
        'Karand Garb',
        'Kangavar',
        'Koozran',
        'Kerendgharb',
        'Gilangharb',
        'Miyan Rahan',
        'Nodesheh',
        'Nowsod',
        'Harsin',
        'Halashi',
      ],
    },
    {
      province: 'Kohgiloyeh va Boyerahmad',
      cities: [
        'Basht',
        'Patawe',
        'why M',
        'Chitab',
        'Dome',
        'Dehdasht',
        'Dishmouk',
        'market',
        'Hard Thirty',
        'Raisi Castle',
        'lower grub',
        'land',
        'lick',
        'Madavan',
        'Margon',
        'Yasuj',
      ],
    },
    {
      province: 'Golestan',
      cities: [
        'Anbaralum',
        'IncheBaroon',
        'Azadshahr',
        'Agh Qala',
        'Porter',
        'Turkmen',
        'Jalin',
        'Khan See',
        'Deland',
        'Ramyan',
        'Red Ice Cream',
        'Third City',
        'Ali Abad',
        'Fazel Abad',
        'Kordkoi',
        'stigma',
        'Galicish',
        'Gorgan',
        'Gamish Tepe',
        'Gonbad-e Qabus',
        'Marawa Tepe',
        'Minodasht',
        'Gem of the city',
        'Node Khanduz',
        'budding',
      ],
    },
    {
      province: 'Gilan',
      cities: [
        'Ahmed Sargorab',
        'Islam',
        'Atakor',
        'amlash',
        'Astara',
        'Astane Ashrafieh',
        'Friday Bazaar',
        'lamb head',
        'Bandar Anzali',
        'head feather',
        'Totkaben',
        'rodent',
        'Agile',
        'Chaf and Chamkhale',
        'Chubber',
        'Hawiq',
        'Kashkbijar',
        'Khamam',
        'Dilman',
        'Rankoh',
        'Rahim Abad',
        'Rostam Abad',
        'Rasht',
        'Rizvanshahr',
        'river',
        'Radbane',
        'Rodser',
        'trench',
        'black',
        'shaft',
        'Shelman',
        'Monastery',
        'Foman',
        'Clacha',
        'Kuchsafhan',
        'Kumle',
        'Kiashahr',
        'Gorab Zarmikh',
        'Lahijan',
        'Lasht Nasha',
        'Lengrod',
        'Lushan',
        'Lulman',
        'Lundville',
        'Lisar',
        'Masala',
        'Masule',
        'Marjgal',
        'Bible',
        'Rental House',
        'Octopus',
      ],
    },
    {
      province: 'Lorestan',
      cities: [
        'Azna',
        'Estrinan',
        'Al-Ashtar',
        'Aligoders',
        'Broujerd',
        'Poldakhter',
        'Challenge',
        'multiple',
        'What',
        'Khorramabad',
        'Dome Door',
        'Hello',
        'slum',
        'Spiddasht',
        'Mirage period',
        'Shul Abad',
        'Firoozabad',
        'Kunani',
        'Mountain',
        'Grub',
        'Usually',
        'Momanabad',
        'Noor Abad',
        'Visyan',
        'Seven Springs',
      ],
    },
    {
      province: 'Mazandaran',
      cities: [
        'Amirkla',
        'Izdshahr',
        'Alash',
        'Amol',
        'Babylon',
        'Babelsar',
        'town',
        'to city',
        'Behnmir',
        'White Bridge',
        'Money',
        'Tenkaben',
        'brook',
        'Chalos',
        'Chamestan',
        'Khorramabad',
        'Khalil Shahr',
        'Khos Rudapi',
        'Dabudasht',
        'Ramsar',
        'Rostamkola',
        'Royan',
        'Rine',
        'neighborhood jeweler',
        'Underwater',
        'Sari',
        'Sarkhrod',
        'Salman Shahr',
        'Sork',
        'Milkhouse',
        'song',
        'Abbas Abad',
        'Fereydunkenar',
        'frame',
        'Governor of the city',
        'Katalum Vasadat Shahr',
        'Klarabad',
        'Klardasht',
        'Heads up',
        'Kohikhil',
        'Caesar',
        'Kiakla',
        'Gotab',
        'Zanek',
        'throat',
        'Mahmoud Abad',
        'Marzan Abad',
        'Merzikla',
        'Nashtarud',
        'Naka',
        'the light',
        'Nowshahr',
      ],
    },
    {
      province: 'Markazi',
      cities: [
        'Arak',
        'threshold',
        'Reconciliation',
        'Bird',
        'surfing',
        'Torre',
        'Javersian',
        'Khashkrod',
        'Khomin',
        'Ditch',
        'Dawoodabad',
        'Dilijan',
        'Razqan',
        'angle',
        'Sarouq',
        'Saveh',
        'Sanjan',
        'Shazand',
        'New City of Mihajran',
        'Ghargabad',
        'Formahin',
        'Be a mouse',
        'Karhrud',
        'Kamijan',
        'Mamony',
        'localities',
        'Milajard',
        'Naraq',
        'Nobran',
        'Neymor',
        'Hindodor',
      ],
    },
    {
      province: 'Hormozgan',
      cities: [
        'Abu Musi',
        'Bastek',
        'Banderjask',
        'Bandcharak',
        'Bandar Abbas',
        'Lengeh seaport',
        'Bikah',
        'Persian',
        'bed',
        'wing',
        'Haji Abad',
        'Dough',
        'Darghan',
        'Deh Barz',
        'Royder',
        'Ziarat Ali',
        'Sardasht Beshagard',
        'Sargaz',
        'Sandrak',
        'Sousa',
        'Sirik',
        'graduates',
        'Finn',
        'Qeshm',
        "Qadi's Castle",
        'Kong',
        'Kushkinar',
        'Kish',
        'Gohran',
        'Minab',
        'Hormuz',
        'octagon',
      ],
    },
    {
      province: 'Hamedan',
      cities: [
        'Azandrian',
        'Asadabad',
        'Barzul',
        'Spring',
        'Twiserkan',
        'Jorqan',
        'Jokar',
        'tail',
        'resin',
        'poor',
        'Saman',
        'leaders',
        'Sweet Sue',
        'Saleh Abad',
        'Famenin',
        'Frosafaj',
        'Firozan',
        'Qorweh in Jezin',
        'Khawand',
        'Blue Song',
        'hill flower',
        'Gyan',
        'Laljin',
        'Orange',
        'Malair',
        'Nahavand',
        'Hamedan',
      ],
    },
    {
      province: 'Yazd',
      cities: [
        'Abar Kooh',
        'Ahmedabad',
        'Dardan',
        'Tears',
        'successful',
        'Befroye',
        'Behabad',
        'Taft',
        'Hamidia',
        'Khizrabad',
        'Dihuk',
        'Zarch',
        'testimony',
        'Tabas',
        'Ashgabat',
        'Kada',
        'Morost',
        'Mohrdasht',
        'Mehriz',
        'gives',
        "don't know",
        'Nair',
        'Herat',
        'Yazd',
      ],
    },
  ],
};
