export const iranProvinces = {
  persian: [
    'اردبیل',
    'اصفهان',
    'البرز',
    'ایلام',
    'آذربایجان شرقی',
    'آذربایجان غربی',
    'بوشهر',
    'تهران',
    'چهارمحال وبختیاری',
    'خراسان جنوبی',
    'خراسان رضوی',
    'خراسان شمالی',
    'خوزستان',
    'زنجان',
    'سمنان',
    'سیستان وبلوچستان',
    'فارس',
    'قزوین',
    'قم',
    'کردستان',
    'کرمان',
    'کرمانشاه',
    'کهگیلویه وبویراحمد',
    'گلستان',
    'گیلان',
    'لرستان',
    'مازندران',
    'مرکزی',
    'هرمزگان',
    'همدان',
    'یزد',
  ],
  english: [
    'Ardebil',
    'Esfahan',
    'Alborz',
    'Ilam',
    'East Azarbaijan',
    'Western Azerbaijan',
    'Bushehr',
    'Tehran',
    'Chaharmahal va Bakhtiari',
    'southern Khorasan',
    'Khorasan Razavi',
    'North Khorasan',
    'Khuzestan',
    'Zanjan',
    'Semnan',
    'Sistan va Baluchestan',
    'fars',
    'Qazvin',
    'Qom',
    'Kurdistan',
    'Kerman',
    'Kermanshah',
    'Kohgiloyeh va Boyerahmad',
    'Golestan',
    'Gilan',
    'Lorestan',
    'Mazandaran',
    'Central',
    'Hormozgan',
    'Hamedan',
    'Yazd',
  ],
};
